# Generated by Django 3.2.6 on 2024-02-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='amount',
            field=models.FloatField(default=1, verbose_name='Amount'),
            preserve_default=False,
        ),
    ]
